# Change these first
owner: Captn138 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main blog (https://www.jaajeur.xyz)
    url: https://www.jaajeur.xyz
    icon: https://www.jaajeur.xyz/assets/img/favicons/favicon-96x96.png
  - name: Minecraft server (mc.jaajeur.xyz:25565)
    check: "tcp-ping"
    url: minecraft.jaajeur.xyz
    port: 25565
    icon: https://raw.githubusercontent.com/Captn138/status/master/assets/minecraft.png
  - name: Minecraft dynamic map (https://minecraft.jaajeur.xyz)
    url: https://minecraft.jaajeur.xyz
    icon: https://minecraft.jaajeur.xyz/images/dynmap.ico
  - name: Feed The Beast server (ftb.jaajeur.xyz:25565)
    check: "tcp-ping"
    url: ftb.jaajeur.xyz
    port: 25565
    icon: https://feed-the-beast.com/favicon.ico
  - name: Terraria server (terraria.jaajeur.xyz:7777)
    check: "tcp-ping"
    url: terraria.jaajeur.xyz
    port: 7777
    icon: https://terraria.org/favicon.ico
  - name: Jenkins pipeline (https://jenkins.jaajeur.xyz)
    url: https://jenkins.jaajeur.xyz/login
    icon: https://jenkins.jaajeur.xyz/static/7222d937/images/svgs/logo.svg
  - name: Jellyfin (https://stream.jaajeur.xyz)
    url: https://stream.jaajeur.xyz
    icon: https://jellyfin.org/favicon.ico
  - name: SMB NAS
    check: "tcp-ping"
    url: jaajeur.xyz
    port: 139
    icon: https://raw.githubusercontent.com/Captn138/status/master/assets/smb.png
  - name: OpenVPN
    check: "udp-ping"
    url: jaajeur.xyz
    port: 1194
    icon: https://openvpn.net/wp-content/uploads/cropped-openvpn-32x32.png

status-website:
  theme: night
  favicon: https://www.jaajeur.xyz/assets/img/favicons/favicon-96x96.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jaajeur.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://www.jaajeur.xyz/assets/img/favicons/favicon-96x96.png
  #https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jaajeur status
  introTitle: "**Jaajeur** : I code and I play games."
  introMessage: This list contains all my publicly accessible services. Most of them are password or whitelist protected. If you wish to access one of them, please DM **Captn138#0505** on Discord.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://www.jaajeur.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
